Minimize on startup
Martichou/rquickshare pull request #55
Opened 2024-04-05 13:04 UTC by tatejuan12

Added feature to start RQuickShare hidden in taskbar. Also added a toggle that can set the feature on or off. Set on as default, given I believe no one wants to have RQuickShare open up on startup.

This is my very first OS contribution, so please advise if I am doing something wrong!

Developed and tested on Arch Linux, Plasma 6.

2024-04-09 10:06 UTC, Martichou commented
Hey! Thanks, I'll check that asap but I'm a bit busy currently :)

2024-04-15 21:08 UTC, Keleva commented
Hay forma de hacerlo correr al inicio sin abrir la GUI, en gestores de pantalla como awesomeWM o bspwm?, saludos.

2024-04-22 08:23 UTC, Martichou requested changes
I'd prefer this to be disabled by default as I may see this cause a small quirk.

If a computer is slow enough, the widow can popup and then disappear  before the minimize_window_on_startup in the setup is called. So until more testers report it working correctly, I'd keep it disabled by default.

2024-04-22 08:23 UTC, Martichou commented on frontend/src-tauri/src/store.rs
> +        Ok(r) => r.unwrap_or(false),
should this return True by default as your intention was to minimize by default?

2024-04-22 08:23 UTC, Martichou commented on frontend/src-tauri/src/store.rs
> +        Ok(r) => r.unwrap_or(false),
see my general comment too

2024-04-22 08:23 UTC, Martichou commented on frontend/src-tauri/src/main.rs
> +#[tauri::command]
can you move that to a separate file like to other cmds?

2024-04-22 08:23 UTC, Martichou commented on frontend/src-tauri/tauri.conf.json
> +      }
not needed afaik

2024-04-22 08:23 UTC, Martichou commented on frontend/src/components/HomePage.vue
> +
remove

2024-04-22 08:23 UTC, Martichou commented on frontend/src/components/HomePage.vue
> +
space

2024-04-22 08:23 UTC, Martichou commented on frontend/src/components/HomePage.vue
> +
remove

2024-04-22 08:23 UTC, Martichou commented on frontend/src/components/HomePage.vue
> +
remove

2024-06-03 02:44 UTC, bruglet commented
How do we test this so it can get merged in?

2024-06-04 17:16 UTC, Martichou commented
As there's no update from @functionalities I'll make the requested changes myself once I have some spare time :) after that it should be good to go.

2024-08-05 22:59 UTC, closed without merging

2024-08-05 22:59 UTC, Martichou commented
Done here: https://github.com/Martichou/rquickshare/commit/eac7dab0dcd8b609cd021f7f29d1e558dca4472c